environment: development

# Server configuration
server:
  port: 8080
  timeout: 30s
  read_timeout: 15s
  write_timeout: 15s
  max_header_bytes: 10 # 1MB

database:
  driver: postgres
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  name: document_api
  ssl_mode: disable
  max_idle_connections: 10
  max_open_connections: 100
  connection_max_lifetime: 1h

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

jwt:
  secret: e#l,8"M5KRTyqJ-LG2"h.0t.|)|I40o,L(h!WC5L.9)Lh-GTK@.A+,4?J(][}X:jl.?eco'q}--=|ta'BUjZ("="kjG,Z|+@#'!j;BK69yMP5mU)];mA!4WLRD+2Q.PK2Q'U+f-M.Z2dD3:}"\Qb[G12u;=.#pR'sLC-|a+LC|XiX(.xyUkX.dgdT[Rex?"[Aql1Exws9+]UqH6\Y67."pW6fWC,cG.YkeulYgAot:z)yi73z4tevwE:h@qy|
  access_token_expiry: 15m
  refresh_token_expiry: 168h

logging:
  level: debug # debug, info, warn, error
  format: json # json, console

rate_limit:
  requests: 100
  duration: 1m