environment: development

# Server configuration
server:
  port: 8080
  timeout: 30s
  read_timeout: 15s
  write_timeout: 15s
  max_header_bytes: 10 # 1MB

Fdatabase:
  driver: postgres
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  name: document_api
  ssl_mode: disable
  max_idle_connections: 10
  max_open_connections: 100
  connection_max_lifetime: 1h

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

jwt:
  access_token_expiry: 15m
  refresh_token_expiry: 168h

logging:
  level: debug # debug, info, warn, error
  format: json # json, console

rate_limit:
  requests: 100
  duration: 1m